### ISSUE TITLE
Various methods can be made less accessible to increase encapsulation

### ISSUE THREAD

**Issue by smieras** [vidstige/jadb#100]
I have noticed that the following methods are declared public:

- AdbProtocalHandler.send()
- DeviceWatcher.watch()
- SyncTransport.readInt() and readString()
- Transport.readString() on line 43 and getCommandLength()

Unless these methods are called by name via reflection, these members should be private to improve information hiding.

If this change is indeed regarded as desirable, I could make a PR for it.

**Comment by vidstige** [comment]
* `DeviceWatcher.watch()` I thought this was the actual function you called to watch for new connections?
* `AdbProtocalHandler.send()` - Sure, sounds good :+1: 
* `SyncTransport.readInt()` and `SyncTransport.readString()` - Sure, sounds good :+1: 
* `Transport.readString()` - This should probably be used somewhere? Seems strange to me. Let's leave as public.

Thanks for checking in first. Looking forward to pr :-)
