### ISSUE TITLE
Is Adb Server possiblely convert to Java?

### ISSUE THREAD

**Issue by Trumeet** [vidstige/jadb#101]
I saw that the project is the client of Adb, it creates socket connection to Adb Server. Is it possible to make a Adb Server in Java?

**Comment by vidstige** [comment]
It's possible, but unwise. The problem is you work with the OS level USB interface to communicate with the device. I've never heard of such enterprise, but I'm pretty sure it can be done. Normally I would advice a language like C or perhaps C++ for this type of task.

**Comment by vidstige** [comment]
@mirfatif this implementation is already present in jadb. There is an almost complete server implementation used in the automatic tests. However, it still does not help with the original problem of talking directly to a phone only using java - You still need the USB parts. However, if there was a way to run via network, that would be awesome. In adb the adb damon is running on the phone, the adb server and client is running on the controlling computer. So in this case I guess either the adb server would need to run on the phone somehow, _or_ if it is possible to create a adb _daemon_ client.

**Comment by mirfatif** [comment]
I'm just a hobbyist developer, so I can talk noobish.

> I guess either the adb server would need to run on the phone somehow ...

Yeah that's the point. ADBLib client can connect to ADB daemon (`adbd` already running in `tcpip` mode obviously) over network socket without running ADB server on phone. This is what I tested:
```
String command = "ping -c3 1.1.1.1";

Socket socket;
try {
  socket = new Socket("127.0.0.1", 5555);
} catch (IOException e) {
  e.printStackTrace();
  return;
}

File pvtKey = new File(getFilesDir(), "pvt.key");
File pubKey = new File(getFilesDir(), "pub.key");

AdbBase64 adbBase64 = data -> Base64.encodeToString(data, Base64.NO_WRAP);
AdbCrypto crypto = null;
try {
  crypto = AdbCrypto.loadAdbKeyPair(adbBase64, pvtKey, pubKey);
} catch (InvalidKeySpecException | IOException | NoSuchAlgorithmException ignored) {
}

if (crypto == null) {
  try {
    crypto = AdbCrypto.generateAdbKeyPair(adbBase64);
    crypto.saveAdbKeyPair(pvtKey, pubKey);
  } catch (NoSuchAlgorithmException | IOException e) {
    e.printStackTrace();
    return;
  }
}

AdbConnection adb;
try {
  adb = AdbConnection.create(socket, crypto);
} catch (IOException e) {
  e.printStackTrace();
  return;
}

try {
  adb.connect();
} catch (IOException | InterruptedException e) {
  e.printStackTrace();
  return;
}

AdbStream stream;
try {
  stream = adb.open("shell:" + command);
} catch (IOException | InterruptedException e) {
  e.printStackTrace();
  return;
}

while (!stream.isClosed()) {
  try {
    Log.e("Test", new String(stream.read()));
  } catch (InterruptedException e) {
    e.printStackTrace();
    return;
  } catch (IOException e) {
    Log.e("Test", new String(e.toString());
  }
}
```
However there are some limitations I observed: https://github.com/tananaev/adblib/issues/4.

So is it possible to achieve the same with `jadb` without relying on the native `adb` binary on phone?

**Comment by vidstige** [comment]
It's currently not possible as far as I know, but it should definitely be possible then. Still, there would be nice pure-java adb server. But instead we would connect to a adb server on the phone, or talk directly to the adb deamon. There is possibly another protocol in use there.
