### ISSUE TITLE
Double quoting

### ISSUE THREAD

**Issue by vidstige** [vidstige/jadb#105]
`Bash.quote()` in `PackageManager.remove()` probably causes double quoting.

**Comment by vidstige** [comment]
Great! :-) So this issue was first reported by @janosvitok in #84. As you can read in the title he hasn't verified this, but just from reading the code, he got suspicious. The problem is that `Bash.quote()` seems to be called twice.

1. First clone the code and run the test suite against an emulator (or real device f you prefer)
2. Verify the bug by installing a package _white a space_ e.g. on an emulator using the `PackageManager` class.
3. If it is indeed there, try to come up with a solution. And write it here. 

If you have any questions - Please let me know.

**Comment by jevalen4868** [comment]
I appreciate the rundown, Samuel!

Per #90 , it seems that the issue has been verified non existent.

For example, when running Bash.quote on 'space file' you get

```
''\''space file'\'''
```

which would translate to:
QUOTE -> UNQUOTE -> CHAR QUOTE -> QUOTE -> 
COMMAND ->
UNQUOTE -> CHAR QUOTE -> QUOTE -> UNQUOTE

This may be redundant but I don't believe it's incorrect.

Your thoughts?
Jeremy

**Comment by jevalen4868** [comment]
Please ignore the last message.

**Comment by vidstige** [comment]
Sweet! Out of curiosity - How did you verify it? For extra credit it's also possible to check in any such verification code as a unit test to keep the code working. 👍 

Thanks for your contribution. And congrats to first merged pr :-)

**Comment by jevalen4868** [comment]
Hey! 

The pleasure's all mine!

I verified by sticking an "ls" execute on the apk name, to see whether or not the file was still there after "rm" execution. I think I could come up with a way to validate that.

Thanks so much for the opportunity to help out.

**Comment by jevalen4868** [comment]
Question:

It looks like we can verify that the file was deleted by issuing the `rm -v`. It'll print out the file path + name of the file if deleted successfully. In addition to (or instead of) a test, would it be reasonable to throw an exception or log a warning if that does not operate as expected?

Thanks!

**Comment by vidstige** [comment]
Thanks for the research. That verification should not be needed. On the android side of things, unless otherwise stated, things works. So if we would like to verify the file was deleted, it's better to check the return code of the `rm` invokation.

I was more thinking of a _unit test_, e.g. code that is run to verify the integrity of jadb, rather than code that is ran when e.g. installing an apk.  See the [existing tests](https://github.com/vidstige/jadb/blob/master/test/se/vidstige/jadb/test/unit/PackageManagerTest.java) for example.

**Comment by jevalen4868** [comment]
Understood, I'll look into it, thanks!
