### ISSUE TITLE
JadbConnection(ip,port)

### ISSUE THREAD

**Issue by Will0376** [vidstige/jadb#107]
Hello! I use your library and I can not understand ...
When you connect to the phone by "adb connect ip" - All OK.
But if you use jadb in java - nothing happens ...
log:
test
test2
Android Device with serial null
test3;

I tried both with the included adb server and without it...
What do I do not so?
P.s.Forgive for awful English

`
th = new Thread(new Runnable() {

			@Override
			public void run() {
				System.out.println("test");
				try {
					jadb = new JadbConnection(textip.getText(), 5555);
					System.out.println("test2");
					System.out.println(jadb.getAnyDevice());
					System.out.println("test3");
					BufferedReader br = new BufferedReader(new InputStreamReader(jadb.getDevices().get(0).executeShell("uname -a"), "UTF-8"));
					System.out.println(br.lines().collect(Collectors.joining(System.lineSeparator())));
				//	List<JadbDevice> devices = jadb.getDevices(); //not work too
					System.out.println("test33");
					System.out.println(jadb.getDevices().get(0).getSerial());
					System.out.println("test4");
					//System.out.println(devices.get(0).getState());
				} catch (IOException | JadbException e) {
					e.printStackTrace();
				}
				System.out.println("test1");
			}
		});	
			th.start();`

Host:
Windows 10.
java version "1.8.0_161"
IDE - eclipse

Phone:
Blackview A7; android 7.0(root); I used the different WiFi adb programs

**Comment by Will0376** [comment]
Hmm, I tried the connection using the usual adb - after the adb connect, the JADB starts working like a cable, but via wi-fi: D

**Comment by vidstige** [comment]
I don't fully understand what you are trying to do here. But I'm glad it worked out in the end! :-)
