### ISSUE TITLE
Problem with connection to VirtualBox by Genymotions

### ISSUE THREAD

**Issue by wenny611** [vidstige/jadb#108]
Hi. I have last Genymotion installation:
Genymotion: 2.12.2
Genymotion emulator: Custom Phone - 6.0.0 - API 23 - 768x1280
VBox: 5.2

Adb running inside the emulator on localhost:5555. [SimpleAdbClient](http://www.source-code.biz/snippets/java/SimpleAdbClient/) works fine. But Jadb with the same input and environment hangs up. Tryed other local and external IPs without any effect.

I also using Jadb in vanila emulators on port 5037 without any problem.

Thx.

**Comment by vidstige** [comment]
Thanks for reporting this. Can you post the output of `adb devices` here? 🤔

**Comment by vidstige** [comment]
Thanks @TheQmaks for clarifying this use case. Let's close for now.
