### ISSUE TITLE
Add support for maven/gradle

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#11]
Please add maven/gradle support to you project to be able to use [https://jitpack.io] to add your project as dependencies to my own project

jadb/v1.0 build
Log https://jitpack.io/com/github/vidstige/jadb/v1.0/build.log

**Comment by vidstige** [comment]
Great! :+1:  Can you make a pull request for this?

**Comment by SKART1** [comment]
Yep - this pull request add `pom.xml` - main file which describes structure and base steps of building project (see more in [maven pom](https://maven.apache.org/pom.html)) - actually it is taken from another fork and little bit refactored. 

When building new version of you library you only need to increase version in this section: 

```
<groupId>se.vidstige</groupId>
<artifactId>jadb</artifactId>
<version>1.0.0-SNAPSHOT</version>
```

[jitpack](https://jitpack.io) vorks a little bit differently. It takes groupId, artifactId and version id from repository name, project name and **tag** ignoring actual values from pom.xml. So using your project as maven dependencies somebody who want to use it just need to write:

```
<dependency>
    <groupId>com.github.vidstige</groupId>
    <artifactId>jadb</artifactId>
    <version>v1.0</version>
</dependency>
```

Last sentense may be added to README.md =)

**Comment by vidstige** [comment]
Yeah, so this is an [issue](https://guides.github.com/features/issues/), please also make a [pull request](https://help.github.com/articles/using-pull-requests/), that way I can accept your code (and documentation) changes.

Suggestion to also edit `README.md` is a good idea, can you please also include this in the pull request?

**Comment by SKART1** [comment]
Updated. Pull-request is [here](https://github.com/vidstige/jadb/pull/13)

**Comment by SKART1** [comment]
Conflict resolved. Just fixed the same test case as was already fixed

**Comment by vidstige** [comment]
Great, thanks for your contribution :+1:
