### ISSUE TITLE
How to block until "am dumpheap" via executeShell until the dump actually finishes?

### ISSUE THREAD

**Issue by farrukhnajmi** [vidstige/jadb#111]
I use the following groovy code to do a heapdump and pull dump file from device:

```
    File getHeapDump(String packageName, String tag) {
        String fileName = packageName + '-'+ tag + '.hprof'
        String dumpFilePath = '/data/local/tmp/' + fileName
        String localFilePath = System.getProperty('java.io.tmpdir') + File.separator + fileName

        // Delete any old dumpfile matching name
        jadbDevice.executeShell('rm', '-f', dumpFilePath)
        jadbDevice.dump()

        // get pid for process matching package name
        int pid = getPidForProcess(packageName)

        jadbDevice.executeShell('am', 'dumpheap', pid.toString(), dumpFilePath)

        String str = jadbDevice.executeShell('am', 'dumpheap', pid.toString(), dumpFilePath)
                .withCloseable { inputStream ->
            String str = IOUtils.toString(inputStream, StandardCharsets.UTF_8).trim()
            if (!str.isEmpty()) {
                throw new ClientException(String.format("Error getting heap dump: %s", str))
            }
            return str
        }

        // Pull heap dump file from device
        RemoteFile remoteFile = new RemoteFile(dumpFilePath)
        File localFile = new File(localFilePath)

        jadbDevice.pull(remoteFile, localFile)

        return localFile
    }

```

The file exists as non-zero bytes file in remote.
The localFile is created with zero bytes.

However, if I run my test in a debugger and hit a breakpoint at the return statement at the end then localFile is created  with non-zero (correct) bytes.

After some testing it turns out that the executeShell does not wait for "am dumpheap" to actually finish. The pull happens too early and that is why the zero bytes.

Adding a sleep before the pull command fixes the problem.

Is there a way for executeShell to block until the dump is finished?

**Comment by farrukhnajmi** [comment]
I figured it out. After the`jadbDevice.executeShell('am', 'dumpheap', pid.toString(), dumpFilePath)` command I need to wait some time before the dump is finished. Putting a sleep before doing the pull command makes things work. 

So is there a way to block until the "pm dumpheap" is actually done?

**Comment by vidstige** [comment]
There probably is such as way, but this is not related to jadb, but rather to the Activity Manager (`am`) command line tool.
