### ISSUE TITLE
DeviceDetectionListener useless

### ISSUE THREAD

**Issue by TheQmaks** [vidstige/jadb#113]
My steps:
1) Run java program with listener
2) adb connect ip:port
3) We get nothing

If i create new thread with while loop and delay printing connection.getDevices().size() - it updated and print me newer devices list. But to listener it doesn't go.

**Comment by vidstige** [comment]
I never liked the Listener anyway. Does not feel like core jadb stuff. I would rather remove it than fix it.

**Comment by TheQmaks** [comment]
I just used getDevices method in loop with checking already added devices by serial. So you can remove it if you like.

**Comment by vidstige** [comment]
Waiting a while to see if someone wants to help out with this, before I jump onto it.

**Comment by TheQmaks** [comment]
I not see listeners in adb server documentation. So i think it better solution, for now.

**Comment by janosvitok** [comment]
We use DeviceWatcher with no problems (ADB over direct USB connection). I would prefer that it stays :)

**Comment by janosvitok** [comment]
Anatoliy, can you post code snippet how do you start the device listener?

**Comment by TheQmaks** [comment]
> @TheQmaks, can you post code snippet how do you start the device listener?

It depends on your devices.

**Comment by janosvitok** [comment]
> > @TheQmaks, can you post code snippet how do you start the device listener?
> 
> It depends on your devices.

This is not a useful answer. My question was in fact offer to debug your code, since for us it works, so maybe you have some problem in your code (or not). For that, I need to see your code.

**Comment by TheQmaks** [comment]
> > > @TheQmaks, can you post code snippet how do you start the device listener?
> > 
> > 
> > It depends on your devices.
> 
> This is not a useful answer. My question was in fact offer to debug your code, since for us it works, so maybe you have some problem in your code (or not). For that, I need to see your code.

:D
I need test it, just wait

**Comment by TheQmaks** [comment]
> > > @TheQmaks, can you post code snippet how do you start the device listener?
> > 
> > 
> > It depends on your devices.
> 
> This is not a useful answer. My question was in fact offer to debug your code, since for us it works, so maybe you have some problem in your code (or not). For that, I need to see your code.

Something like that. If you want, you can make your listener for events like a ConnectedDevice and DisconnectedDevice. All in your hands.
https://pastebin.com/KyT4gUnA

**Comment by vidstige** [comment]
But the listener is passive and event driven, while the above code is polling. Let's keep the `DeviceDetectionListener` for now. I still don't like it thought. :-) It would be cool if we could decouple the threading there, so that the users of the library had to create their own thread, and have the threading code as example code or something like this.
