### ISSUE TITLE
Quoting is insufficient

### ISSUE THREAD

**Issue by electromatter** [vidstige/jadb#123]
The quoting added by #69 is insufficient. You quote space characters, but one should also quote strings that contain special characters as specified by POSIX given https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_02 . 
However, this can vary from shell to shell, so to be safe you should quote all strings. As it stands now, this library incorrectly quotes strings, for example arguments that do not contain spaces but have a $WORD would be interpreted as a variable substitution instead of the string '$WORD'. Correct quoting should quote all strings.

**Comment by root-intruder** [comment]
fixed by #135, so this can be closed
