### ISSUE TITLE
.executeShell doesn't work with large commands and multiple arguments

### ISSUE THREAD

**Issue by shill829** [vidstige/jadb#126]
I am writing a program to automatically test certain info about the device. I'm having trouble using large commands, however. For example, the command **

dumpsys battery \|   grep '^  level:' \|sed   's,.*\(.\{3\}\)$,\1,'\|awk '{$1=$1};1'
--

**

 

returns only the numerical value of the battery level. However, I cannot run this command sucessfully via .executeShell. It only seems to run the first part.

**Comment by vidstige** [comment]
I think that's to be expected as the `executeShell()` function does not execute a shell (despite it's name), but rather just `exec`'s the given command. Can you try with `bash -c "dumpsys battery | grep '^  level:' "` for example just to try piping works. Note the explicit shell invokation with `bash -c`

**Comment by vidstige** [comment]
This is working as expected and has an easy workaround, so closing for now.
