### ISSUE TITLE
Could you make a new release, please?

### ISSUE THREAD

**Issue by gmmapowell** [vidstige/jadb#128]
I was just trying to diagnose a connection leak issue and found that although it was a problem in the maven version, there looks a very plausible fix in github source.

I see there have been 80 commits since the last release.

It would be great to have these fixes out in the wild.

Thanks!

**Comment by vidstige** [comment]
Great idea!

**Comment by vidstige** [comment]
Just did one. :)

**Comment by gmmapowell** [comment]
Thanks!
