### ISSUE TITLE
Trying to connect android with android

### ISSUE THREAD

**Issue by Gyara2** [vidstige/jadb#133]
Hi! Firstly, I need to know if it is possible connect an android device with an another device using this client.

I want to made an app that could configure an android device which needs a custom configuration (push, pull, etc...)

Currently, when I launch the apk, I get an error "More than one device ...", If I disconnect the host machine (windows) using adb kill-server and click the button another time I get a distinct error, in this case, "JadbException: command failed: device offline".

The problem is that the connection is ok

JadbConnection jadb = new JadbConnection(); // Android Device 1 - "localhost" , "5037"

jadb.connectToTcpDevice(new InetSocketAddress("192.168.1.187" , 5555));

Could you help me with this pls?

**Comment by root-intruder** [comment]
Would you maybe be more specific on errors: stacktrace and the Problem? the title says you want to connect two android devices and in the text you speak of a windows machine you disconnect.

The more than one device error is usually when you have 2 phones connected to the computer and do:
```
JadbConnection adb = new JadbConnection();
adb.getAnyDevice();
```

**Comment by vidstige** [comment]
We need some more information on this to be able to help you. Thanks for helping out with writing an answer @root-intruder

**Comment by kikasik** [comment]
@alvaroguiradoASIR Any success in connecting android with android?

**Comment by vidstige** [comment]
Closing this as it seems somewhat unclear
