### ISSUE TITLE
RemoteFile.getPath() doesn't work as intended?

### ISSUE THREAD

**Issue by KingHabib** [vidstige/jadb#139]
I am using `JadbDevice.list("/sdcard/Test")` to save a list of RemoteDevices in a certain directory. For each of these RemoteDevices, I noticed that calling the `getPath()` method only returns the file name.

For example, I get `"TestFile.txt"` instead of `"/sdcard/Test/TestFile.txt"`. I am unsure if this is the intended result from the method. I am using v1.2.1 from the jitstack maven repo.

**Comment by vidstige** [comment]
Yes, that's expected. Maybe a bit surprising, but the returned paths are to be considered relative to the argument.
