### ISSUE TITLE
Do I need to manually close any connections or devices?

### ISSUE THREAD

**Issue by zhailingzy** [vidstige/jadb#144]

**Comment by hhhaiai** [comment]
you mean: adb connect/adb disconnect?

``` Java
//adb connect 
new JadbConnection().connectToTcpDevice(InetSocketAddress inetSocketAddress)
adb disconnect
new JadbConnection().disconnectFromTcpDevice(InetSocketAddress tcpAddressEntity)
```

**Comment by vidstige** [comment]
Please clarify your questions. In short you don't need (and can't) to close JadbDevice nor JadbConnections. They will create a new connection each time they are used currently. But that might change, if they implement AutoCloseable, use that, otherwwise not.
