### ISSUE TITLE
How does the server module work?

### ISSUE THREAD

**Issue by hhhaiai** [vidstige/jadb#145]
How dose the server module (se.vidstige.jadb.server) work.

**Comment by vidstige** [comment]
Great question!

* There is a general `SocketServer` class that accepts connections and spawns new threads when tcp clients connect.
* There is a specific `AdbServer` and `AdbProtocolHandler` that implements the [adb protocol](https://android.googlesource.com/platform/system/core/+/dd7bc3319deb2b77c5d07a51b7d6cd7e11b5beb0/adb/OVERVIEW.TXT).
* There is a
