### ISSUE TITLE
Java 8 source and target

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#15]
Java 1.8 has better performance and also have some cool stuff like lambdas. And according to latest [reports](http://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-2016-trends/) java 1.8 already used in 62% of projects

**Comment by vidstige** [comment]
I love Java 8, but opted to not use it for this project as the benefits are not _that_ great and it would just exclude people not being able to move to Java 8. However, as you point out, Java 8 is not more widely used. Perhaps it's time to make the switch.

**Comment by SKART1** [comment]
I thought about this idea a little bit more yesterday and I inclining to resume using Java 1.7 for may be half a year or a year more. Because of:
 * 38% of users  is a big amount. Using java 1.8 will not allow them to use this great library. 
 * As Android support only Java 1.7, and most of android developers are more comfort with this version of code  - it will be a little bit more difficult for them to contribute to this project, as understanding the code will be complicated by new features


However, you is an author of the library - so you should decide =)

**Comment by vidstige** [comment]
Yes, I'm inclined to stay on 1.7 for some time as well. Let's do it like that. Hope it don't hurt your other branches too much. I checked through the install options changes and those should mostly be easy to go back to 1.7.
