### ISSUE TITLE
Dependency 'com.github.vidstige:jadb:v1.2.1' not found 

### ISSUE THREAD

**Issue by vedha-vikash-pixel** [vidstige/jadb#151]
I am trying to include the jadb package in my maven project . As mentioned in the Readme file , i have added the jitpack repo and the jadb dependency in my spring boot pom.xml file.

```
<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
</repositories>
</dependencies>
<!-- Other Maven Dependencies -->
                <dependency>
			<groupId>com.github.vidstige</groupId>
			<artifactId>jadb</artifactId>
			<version>v1.2.1</version>
		</dependency>
</dependencies>

```

Intellij is telling me "Dependency 'com.github.vidstige:jadb:v1.2.1' not found "

Can anyone help me to resolve this issue?

**Comment by gbiz123** [comment]
Having the same issue

EDIT: This was easily fixed by restarting my IDE.

**Comment by vidstige** [comment]
It should be available on jitpack. Glad you were able to get it working again. And thanks for sharing with others that might stumble across the same thing.

**Comment by gbiz123** [comment]
If anyone is reading, you may want to try running `mvn dependency:resolve` from the command line to resolve missing dependencies

**Comment by vedha-vikash-pixel** [comment]
Thanks
