### ISSUE TITLE
Remove IDE specific files

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#16]
In repo there is current a lot of files which may help sometimes to import project more easy in IDE, but sometimes they may cause errors in import. In my opinion pure pom.xml  is enough - it allows to import project in any IDE without problems.

Also changing this files make git diffs have garbage

**Comment by vidstige** [comment]
Which file are you referring to? The .intelij folder contains interesting information on how to build the project, I'm not sure if you can just open the pom file as is in IntelliJ, but I will try it out. If that works well, I'm all for removing the InteliJ files. The Eclipse files can go in any event.

**Comment by adelolmo** [comment]
Intellij is definitely able to create a project based on a pom.xml file.
I normally add the .idea directory to the .gitignore so it's never commited.

**Comment by SKART1** [comment]
I am referring to whole `.idea` folder. I will check now if Idea can open project without this folder

 `.classpath` and `.project` - I am not sure (have not run eclipse for programming on Java for more than 2 years)

**Comment by SKART1** [comment]
yes, intellij idea is able to open and import project with droped .idea folder

**Comment by vidstige** [comment]
Hmm, I tried this myself and it would open, but it wouldn't build. Can't quite remember what the error message was. Can you open and build right of the bat? What version if IntelliJ are you running?

**Comment by SKART1** [comment]
I am using Linux - so sorry - no CMD/BAT. But I have executed in pure `bash` (which is actually similar to windows CMD) next commands

```
mkdir temp
cd temp
git clone https://github.com/SKART1/jadb.git     
cd jadb/
git checkout develop
rm -rf .idea   # removing ".idea" folder with intellij-idea specific files
mvn clean package
```

Which resulted in BUILD SUCCESS

P.S. I used my fork of repo becuase of #23 in upstream/master

**Comment by vidstige** [comment]
I'm on mac and can also use bash. The expression "right of the bat" means to be able to do something without extra work. I can also build from command line straight from checkout, however, when opening the jadb directory in [IntelliJ](https://www.jetbrains.com/idea/) it's not possible to build.

**Comment by SKART1** [comment]
Sorry, English is not my native language and I have understand "bat" as "BAT" files from windows. Nevertheless, will try similar scenario in Idea =)

**Comment by vidstige** [comment]
Alright, so we can conclude for now that the .idea folder is needed then.

**Comment by SKART1** [comment]
Sorry, forgot to do actual test

**Comment by vidstige** [comment]
np, I was just closing some stale issues. Feel free to reopen if you find it's not needed for smooth IntelliJ operation.
