### ISSUE TITLE
Support install options

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#17]
In [official documentation](https://developer.android.com/studio/command-line/shell.html#pm) there are a list of supported by `pm install` additional flags. Need to support them in code

**Comment by vidstige** [comment]
Thanks for the feedback! There are lots of things pm can do, quite a lot of them not widely used. Anything in particular you're interested in?

**Comment by SKART1** [comment]
Concretely I am interested in "-g" flag which gives all **Manifset** permissions for new permission system on Android 6.X.

It is also may be important to know that this option is not "backward compability" and make adb daemon to deny installation.

I have made proto. Here is the [link](https://github.com/vidstige/jadb/compare/master...SKART1:IMP-2-install-options) to compare across forks

**Comment by vidstige** [comment]
Looks great! I've only minor comments top of my head. It seems it requires Java 8 support as well, so I suspect you have a brach for that as well somewhere? Care to make a pr? :)

**Comment by SKART1** [comment]
I think I will revert back to Java 1.7 or stay on Java 1.8 depending on your decision in #15 
There are only one little piece of code which uses new lambdas

**Comment by vidstige** [comment]
Feel free to put up pr if you wish to share your code.

**Comment by SKART1** [comment]
Sorry, was on holidays =)
Soon I will downgrade code to java 1.7 and make a PR

**Comment by vidstige** [comment]
Yeah, didn't mean to rush you or anything, sorry if it came across like that. I'm on holidays myself here. :-)

**Comment by SKART1** [comment]
Never mind =)

I have recreated pull-request based on another branch not to mention empty commits
