### ISSUE TITLE
Getting the state of a device

### ISSUE THREAD

**Issue by pijpijpij** [vidstige/jadb#18]
When getting the list of devices (with `JadbConnection.getDevices()`), ADB closes the connection (as per protocol), so the next call (to `JadbDevice.getState()`), fails with 

    se.vidstige.jadb.JadbException: command failed: closed

	    at se.vidstige.jadb.Transport.verifyResponse(Transport.java:39)
	    at se.vidstige.jadb.JadbDevice.getState(JadbDevice.java:46)

That is also true with a device acquired with `JadbConnection.getAnyDevice()`.
There doesn't seem to be any other way getting hold of a device.

What gives? Are there circumstances in which  `JadbDevice.getState()` works?

PS: Thanks for this library. Installing packages work, so it does help quite a lot.

**Comment by vidstige** [comment]
Thanks for your feedback. This is probably a bug recently introduced, when fixing a bug where you could only transfer one file at a time. Will try to reproduce this bug.

**Comment by pijpijpij** [comment]
Thanks. Here is a quick unit test that captures that behaviour:

      @Test
    public void test_jAdbRetrieveAnyDeviceStatus_failsBecauseClosed() throws Exception {
        startAdbServer();
        JadbDevice device = new JadbConnection().getAnyDevice();

        try {
            System.out.println(device.getSerial() + " status=" + device.getState());
        } catch(JadbException expected) {
            assertThat(expected, hasMessage(containsString("command failed: closed")));
            return;
        }

        fail("Should not be here");
    }

where method 'startAdbServer()' simply runs a process with "adb devices" to ensure the server is actually running.

**Comment by pijpijpij** [comment]
Ooops, didn't mean to close this!
