### ISSUE TITLE
ConnectException when unauthorized. 

### ISSUE THREAD

**Issue by woutwoot** [vidstige/jadb#3]
When I try to connect to my device on a new computer, I am greeted with a connection error when just using the following code:
```
JadbConnection jadb = new JadbConnection();
        List<JadbDevice> devices = jadb.getDevices();
        if (devices.size() == 0) {
            System.out.println("No android device running ADB was found. Please connect an android device and enable ADB.");
        }
```
Java ADB java.net.ConnectException: Connection refused: connect

I am not being prompted to allow access for this computer on my phone. When using adb separately first, and allowing access, jadb works. Is there a way jadb could ask for access first? This is on a Windows machine.

**Comment by vidstige** [comment]
This is a great idea! It's mentioned briefly in the README.md, I'm quoting: "Make sure the adb server is running. You can start it by running adb once from the command line.". Making this work more smoothly out of the box, would require somewhat platform-specific details, but it would certainly be sweet.

**Comment by vidstige** [comment]
The latest master tries to start adb either from path or `ANDROID_HOME` environment variable. Please try it out let me know if it works better for you.
