### ISSUE TITLE
Info about device.  Shell command getprop

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#38]
Nevertheless it is just executing of shell command, it may be a very common case - for example determining OS version, language and so on

**Comment by vidstige** [comment]
I don't understand what this is? Sounds great? Is it something that execute a particular shell command and parses the output? There is already code like this for example `PackageManager`, feel free to explain your use case a bit more and what kind of information you are looking for. Or push a few commits and make a pull request. :-)
