### ISSUE TITLE
DeviceDetectionListener onDetect fires double times

### ISSUE THREAD

**Issue by serezhka** [vidstige/jadb#46]
DeviceDetectionListener onDetect fires double times
![capture](https://cloud.githubusercontent.com/assets/476359/21450080/bded6e94-c904-11e6-8013-b2b376a582df.PNG)
Connecting device.. onDetect fires with 'device offline'
![capture111](https://cloud.githubusercontent.com/assets/476359/21450729/70188888-c90a-11e6-8be6-595c0cf323ec.PNG)
And then immediately onDetect fires second time with 'device online'
![capture112](https://cloud.githubusercontent.com/assets/476359/21450733/7451b3f2-c90a-11e6-959b-4f1c96fdb3ef.PNG)
Is it a bug or feature?

### Host
windows 10 x64, java 8  

`$ adb version`
`Android Debug Bridge version`
`1.0.32 Revision eac51f2bb6a8-android`  

jadb version : commit 0cb9550b506ec9888446f9cefb25f76c098e51cf
`new JadbConnection().getHostVersion()` -> 0020

### Android
Samsung galaxy s4 (i9505)
CyanogenMod 14.1 (android version 7.1.1)

#### PS
Thanks for the library, it is very helpful :star:

**Comment by vidstige** [comment]
Thanks for reporting the issue. Those events originate from the adb server, possibly even emitted by the on-device adb daemon. The library by itself does not emitt any extra events, but just forwards what it gets from the adb server. In this case the double events should normally be harmless. Are you having any specific issues?

**Comment by vidstige** [comment]
Perhaps @Giemsa who implemented this can give some insight?

**Comment by Giemsa** [comment]
Adb daemon emits two events when device is connected. AFAIK, the device state changes to `offline` first, but the device is not available. And then the device state changes to `online`, the device is available. This API just sends these events. I suppose you can ignore `offline` event.
