### ISSUE TITLE
Transport class has default access modifier

### ISSUE THREAD

**Issue by serezhka** [vidstige/jadb#47]
JadbConnection createTransport() is useless until [Transport](https://github.com/vidstige/jadb/blob/master/src/se/vidstige/jadb/Transport.java) class has default access modifier

**Comment by vidstige** [comment]
This is more a statement than a problem description. The Transport class is not supposed to be accessed outside package, that's why it has the [default visibility](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html).
