### ISSUE TITLE
Running ADB commands inside Android App

### ISSUE THREAD

**Issue by gokulpalanisamy** [vidstige/jadb#49]
I have requirement like i need to take a UI dump of each activity that appears on my android app to verify resource-id given is unique. I was thinking to use this adb command "adb pull uiautomator dump" and verify the same. So i created a java class in my android app, that uses jadb and it works fine when i run as java application.

But when i run my android app, i am calling the same class with the following details,

            jadb=new JadbConnection("my_ip",5037);
            List<JadbDevice> devices = jadb.getDevices();
            for(JadbDevice device:devices){
                device.executeShell("shell:uiautomator dump");
            }
and the below is my error:

01-23 14:23:41.138 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err: java.net.ConnectException: failed to connect to /<my_ip> (port 5037): connect failed: ECONNREFUSED (Connection refused)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:124)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.startupSocket(Socket.java:590)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.tryAllAddresses(Socket.java:128)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.<init>(Socket.java:178)
01-23 14:23:41.178 23845-23845/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.<init>(Soc

Note:
I am using real device and not emulator.

My question is will i be able to run adb command from/inside an android app like i m trying to do here. ?

**Comment by SKART1** [comment]
The reason of the error is that by default adb server listens only on 127.0.0.1  - listening connections only from same computer it is started. There is a solution for this problem - start adb server with `-a` flag


As for your approach - I think it is much logically to run such a command exactly on your android device via for example [ProcessBuilder](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html) with arguments  `uiautomator dump`. I am not 100% sure - but I think this approach will work

**Comment by gokulpalanisamy** [comment]
Earlier I tried ProcessBuilder, that did not work. 
From the docs, i saw Make sure the adb server is running. You can start it by running adb once from the command line.
So i m doing adb start-server -a and i ran adb devices from my pc, it displayed my device
Now, i open android studio, and from my app code i create an object for my adb class which has the following code,
             jadb=new JadbConnection();
//            jadb=new JadbConnection("my_ip",5037);
            List<JadbDevice> devices = jadb.getDevices();
            for(JadbDevice device:devices){
                device.executeShell("shell:uiautomator dump");
            }

01-23 14:59:38.090 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 5037): connect failed: ECONNREFUSED (Connection refused)
01-23 14:59:38.217 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:124)
01-23 14:59:38.345 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
01-23 14:59:38.439 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
01-23 14:59:38.524 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.startupSocket(Socket.java:590)
01-23 14:59:38.609 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.tryAllAddresses(Socket.java:128)
01-23 14:59:38.704 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.<init>(Socket.java:178)
01-23 14:59:38.802 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at java.net.Socket.<init>(Socket.java:150)
01-23 14:59:38.927 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at se.vidstige.jadb.JadbConnection.createTransport(JadbConnection.java:25)
01-23 14:59:39.021 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at se.vidstige.jadb.JadbConnection.getDevices(JadbConnection.java:36)
01-23 14:59:39.092 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at com.autoMi.ADB.<init>(ADB.java:27)
01-23 14:59:39.198 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at com.autoMi.WindowEventSniffer.<init>(WindowEventSniffer.java:73)
01-23 14:59:39.307 7370-7370/com.example.gokulpalanisamy.firstapp W/System.err:     at

so the above java code will be inside my android app. I am clicking on a button in my android app which calls the above code, that time i m getting the above exception. 

Note:
The same code works when i ran the same as plain java application. So i suspect when it run inside my android app the problem occurs which i m not able to understand.

whether  jadb=new JadbConnection(); this line inside my android app able to connect to server that is listening on default port on my pc ? i am not able to understand this part

**Comment by vidstige** [comment]
Normally you should not run adb from within an android app. You can instead render your root view to file to get predictable and stable results. See more [here](http://stackoverflow.com/questions/2661536/how-to-programmatically-take-a-screenshot-in-android).
