### ISSUE TITLE
can we implement an adb server?

### ISSUE THREAD

**Issue by agirllmy** [vidstige/jadb#56]

**Comment by vidstige** [comment]
Hi,
Could you clarify your question? What are you trying to do. There is already a great adb server made by google. Also, there _is_ an adb server in this package. It's used in the unit tests! :-) Please check it out and see if it suites your needs.

**Comment by SKART1** [comment]
@agirllmy - adb server is actually open source (written in C/C++) and may be modified by anyone.
As for it`s quality - it is not as high as you expect from most popular mobile OS in the world, but it at least updated and supported


What about creating own implementation in java - it will not be easy to maintain at least 3 platforms and supporting hundreds of features which adb now have, nevertheless it is possible and may be an interesting project

**Comment by vidstige** [comment]
Check out [AdbProtocolHandler](https://github.com/vidstige/jadb/blob/master/src/se/vidstige/jadb/server/AdbProtocolHandler.java) - it implments the server side adb protocol. You need to inject a `AdbResponder` to handler commands sent to a specific device. Note: Only the protocol is implemented here, it's used in the unit tests, it can not talk to any device in any way. For this, please use the adb server in the Android Open Source Project (AOSP) found [here](https://android.googlesource.com/platform/system/core.git).

**Comment by agirllmy** [comment]
I want to implement a java program which can talk to a device by using adb protocol，just like the function of adb server.

**Comment by vidstige** [comment]
As I suspected. This will lead you down into a rabbit hole of dealing with hardware, etc. It is not a huge task, especially if you drop x-platform constraints. Some JNI will most likely be needed to access usb hardware. There probably already are libraries for this you can use. For the adb protocol, see the documentation, the adb protocol implemented in this rep and also the source code linked above. Good luck in your endeavors! :)
