### ISSUE TITLE
Getting permission error when pulling from device

### ISSUE THREAD

**Issue by yaron-e** [vidstige/jadb#64]
//String path = "/data/user/0/com.package/files/";
        String path = "/data/user/0/com.package/files/";
	String file = "TEST2.txt";

	JadbConnection jadb = new JadbConnection();
	JadbDevice device = jadb.getDevices().get(0);

	device.executeShell("run-as", "com.package");
	try {
		device.pull(new RemoteFile(path), new File(file));
	} catch (Exception e) {
                    //Keep getting a Permission denied exception
		System.err.println("Error while pulling: " + e.getMessage());
	}

I keep getting Permission denied error when trying to pull a file from the device.
Do you have any ideas on why this is happening and how to solve it?

Thank you

**Comment by vidstige** [comment]
That's because you are not allowed to copy a directory. Try something like this instead.

    device.pull(new RemoteFile("/data/user/0/com.package/files/TEST2.txt", new File("TEST2.txt"));

Hope this helps, let me know otherwise.

**Comment by vidstige** [comment]
Did you have a chance to try this out?

**Comment by vidstige** [comment]
I'll assume this got resolved, feel free to reopen otherwise @yaron-e
