### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by chipsenkbeil** [vidstige/jadb#65]
Any plan to add the dependency to Maven Central? Needing to add jitpack isn't necessarily an option for everyone (including myself). Furthermore, depending on a separate service as opposed to the defacto host (Maven Central) is a bit of a concern for longevity in case jitpack goes away.

**Comment by vidstige** [comment]
I have no such plan. Me and Maven never got along very well. In fact, I got help with fixing this up with jitpack. I totally see the benefits of going Maven Central. Perhaps you could help out in some way? What are the steps to get there, etc?

**Comment by SKART1** [comment]
@chipsenkbeil as for now - you have at least 2 options:
* download jar from jitpack (or compile it from sources) and add it to local lib folder of your project
* add jar to your company`s local artifacts repository (if it exist in your company)

P.S. If you have any manual - please provide it.

**Comment by chipsenkbeil** [comment]
@vidstige, I'll look into getting your project set up with Maven Central. I've done it with a couple of projects before.

**Comment by shubham-negi** [comment]
Hi there, can I try ? If nobody is working on this then please let me know.

**Comment by chipsenkbeil** [comment]
@shubham-negi, go for it. Work sucked me away from this.

**Comment by vidstige** [comment]
@shubham-negi yeah, sure. Go for it. Seems like at least one person would appreciate it. 👍

**Comment by shubham-negi** [comment]
Well I'm new to this very thing. Can somebody be nice to me and help a bit?

**Comment by chipsenkbeil** [comment]
@shubham-negi, with regard to getting access in Maven Central, check out these issues I filed for other organizations.
 https://issues.sonatype.org/browse/OSSRH-16641 <-- Creating an org.senkbeil organization
https://issues.sonatype.org/browse/OSSRH-19500 <-- renaming to org.scala-debugger

I'm not familiar with the tool Maven. Don't know if it has integrated support to push to Maven Central or if it's a plugin. But, should be fairly straightforward to select certain artifacts to publish. See if this [Sonatype post](http://www.sonatype.org/nexus/2015/06/02/how-to-publish-software-artifacts-to-maven-central/) or the official [Maven site](https://maven.apache.org/) has any documentation on this front.

**Comment by bcallebaut** [comment]
@shubham-negi, any progress on it ?

One need to:
- change version from 1.0.0-SNAPSHOT to 1.0.0
- create/distribute/use your PGP public key 
- Setup Sonatype account

**Comment by shubham-negi** [comment]
@bcallebaut No, I didn't started it yet. If you want me to, then I can configure the mentioned list [PS: Except Sonatype, I haven't heard about it yet but I can look it up if you agree ].

**Comment by bcallebaut** [comment]
@vidstige Fully agree. the best is to use your PGP key (if anybody else signing with its PGP key drops out of the project it will be a mess.
@shubham-negi Fine for me but check with vidstige before creating any account on Sonatype. Multiple persons/account involved in pushing an artifact is a bad idea.
@vidstige : I can take on the maven part. For the admininstrative part (accounts...) I prefer that you centralize everything. (if it is fine for you of course). It is a pain the first time but afterwards, it can be automated.

**Comment by vidstige** [comment]
Yes, I've heard there can be a pain and so on. Can someone elaborate on exactly what problem this solves or how this makes the world better? Compare with current setup with jitpack.

**Comment by chipsenkbeil** [comment]
@vidstige, see my initial reasons at the top of the issue.

**Comment by bcallebaut** [comment]
- Maven integration is a defacto standard for the 3 main IDE (Eclipse,IntelliJ & Netbeans)
- Ant is also supported but lacks the dependency management (extensions for ant are not standard or supported by IDEs)
- Project structure and dependency/settings management of the 3 IDEs is incompatible
- gradle projects support natively maven dependencies 
- jadb builds with maven

**In Conclusion**:
 Maven is the only portable project format, combined with a repository & dependency management system supported across the 3 major java IDE.

NB : gradle could also be an option but is not used yet in the project

**Comment by vidstige** [comment]
I think your confusing Maven with Maven Central? I think we already tick all of these bullets, e.g. you can just ignore the ant build and import the pom file into IntelliJ and so on which is very convenient. So let's focus on what benefits we would get from Maven Central, as compared to jitpack. Please be specific. Right now I feel the case for Maven Central is rather weak, considering the extra effort it will take.

**Comment by bcallebaut** [comment]
Downloading manually and tracking versions of 100 of libraries is really time consuming and quickly become a nightmare. Maven handles it smoothly through its transitive dependency management.
It is true that the added value for this project may be small, but it can become a showstopper for users accustomed to handle projects that way. 

That said, I have to problem with the current situation.

**Comment by vidstige** [comment]
I fully agree Maven have a lot of benefits. Let's first recap the current situation.

* Developers _using_ this package (jadb) can easily use Maven for dependency management if they so desire, as described in [the documentation](https://github.com/vidstige/jadb#using-jadb-in-your-application).
* Developers of _this_ package (jadb) can build it using Maven, either from command line or via IDE of choice. Successful Maven invocation for reference can be found in the [latest build log](https://travis-ci.org/vidstige/jadb/jobs/362207764#L450).

My understanding of the benefits for Maven Central
* the jitpack service may or may not be there to morrow.
* jitpack is not an option to everyone (unspecified as to why?)

My understanding of the benefits for Jitpack
* Literally zero config, no buttons to press, users to create, and so on. Just works. 
* Each build is published detecting problems early.
* For open source projects, there is always the risk of maintainers dop out, etc. So there is a charm with a service that Just Works ™️ 

Right now, I don't feel I have the time and energy to go through the hoops of Maven Central for the, to put it mildly, vague benefits it might provide.

**Comment by vidstige** [comment]
Let's reopen if the circumstances or reasons for Maven Central changes.
