### ISSUE TITLE
sending unicode characters

### ISSUE THREAD

**Issue by emanresusername** [vidstige/jadb#67]
one of those days where "not even thinking about it, assumed it'd be a no-op" turned into "where'd the day go :open_mouth:" 😅 
curious how you'd go about sending unicode characters/emoji to the `execute` command?
thought it'd be as simple as `jadbDevice.execute("input", "text", "😀")`
then came across [this stackoverflow](http://stackoverflow.com/questions/14224549/adb-shell-input-unicode-character) and [this repo](https://github.com/senzhk/ADBKeyBoard)
that seemed to work on the shell (with the exception of mixing in some special characters `() '`) but i [ended up stumped on how to get it working from the jvm :sob:](https://github.com/emanresusername/scalandroid/commit/f1113f1d1ef9262a203bf5a84db48ca56bc679bb)
any ideas?

```scala
val shades: String = """(•_•)
( •_•)>⌐■-■
(⌐■_■)
"""
val processArgs = Seq("adb", "shell", "am", "broadcast", "-a", "ADB_INPUT_TEXT", "--es", "msg", "'" ++ shades ++ "'")
val executeArgs = processArgs.drop(3) // just from `broadcast` through `shades`
val process = new ProcessBuilder(processArgs:_*)
process.start // works
jadbDevice.execute("am", executeArgs:_*) // /system/bin/sh: no closing quote
```
that was the gnarliest example (newlines, spaces, parens AND unicode chars) but just regular solo emoji also work from the process builder but fail from the `execute` method

**Comment by vidstige** [comment]
This is not a problem with the `jadb` project, nor with the `adb shell` subcommand. But this is a problem with the `input` program on the android device. As you have noticed it cannot accept unicode. But the workaround with the keyboard sounds like a great work-around, no? Did you try that keyboard?

Also unrelated, I think you can call Java code from Scala, so no need to port this library, unless you enjoy it of course. :-)

**Comment by emanresusername** [comment]
yeah was just curious if you had any ideas/pointers

I did end up using that keyboard and just calling out to the [`ProcessBuilder`](http://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html#ProcessBuilder(java.lang.String...)), works well enough for me ¯\_(ツ)_/¯

indeed you can! 
mine is *definitely* not a port of this library! just basically a wrapper, calling out to it with a few parameters that were accumulating in my repl history/had to search online a lot for and wanted to commit somewhere 😅

**Comment by vidstige** [comment]
Ah, I see. No, I don't have any good pointers really, I'm afraid. I would start by double-checking the source code of the `input` program to see if there isn't really any way to escape characters. I'm guessing there is not.... :-/
