### ISSUE TITLE
Quote arguments with e.g. tabs

### ISSUE THREAD

**Issue by vidstige** [vidstige/jadb#69]
When executing commands on the android device e.g. `adb shell ls /`strings without spaces are not quoted at all, just to give better error-messages, log printouts, etc.

This breaks down if a tab character is passed to the `execute()` function, e.g. like so `device. execute("echo", "a\tb")`;

To fix this the `Bash.quote` function should be little bit more clever and also quote strings containing tabs or newlines, see more [here](https://github.com/vidstige/jadb/blob/6ec1a4f9f9058df756d92ea8e296e966df5999c5/src/se/vidstige/jadb/managers/Bash.java#L5).

Let me know if you have any questions.

**Comment by muhikhsan101** [comment]
May I take this issue?

**Comment by vidstige** [comment]
Hi, thanks for showing interest in the `jadb` project!

I think this will be much to easy for you, but be my guest! :) Please also add a unit test for this case, preferably [here](https://github.com/vidstige/jadb/blob/master/test/se/vidstige/jadb/test/unit/MockedTestCases.java).

**Comment by muhikhsan101** [comment]
Sure, will do.

You may say so, this will be my first time making a PR.
