### ISSUE TITLE
compare with ddmlib

### ISSUE THREAD

**Issue by herau** [vidstige/jadb#73]
Hello,

Just wondering if jadb has features ddmlib doesn't have ?

Because i guess ddmlib is the official way to discuss with adb ?

https://mvnrepository.com/artifact/com.android.tools.ddms/ddmlib/22.0

Thanks for your answer

Best regards

**Comment by xcjiang** [comment]
i was wondering too, any explanation?

**Comment by vidstige** [comment]
I'm not fully aware of the features of ddmlib, but I doubt jadb has something ddmlib does not. I originally wrote the jadb library to verify the official Android documentation on the adb protocol which I have described. One should see `jadb` as a mini-implementation of the protocol. It's great if you want to play around with the protocol and learn how stuff works. But it's very mature also and if you like it there is nothing stopping you from using it in more serious settings.
