### ISSUE TITLE
conflict access modifier

### ISSUE THREAD

**Issue by thangdc94** [vidstige/jadb#74]
`createTransport()` is public, but return `class Transport` is package access.
```
public Transport createTransport() throws IOException {
        return new Transport(new Socket(host, port));
    }
```

**Comment by vidstige** [comment]
Good catch, will look into it. Or accept prs, if you're so inclined.  I guess both should be package... :thinking:

**Comment by bcallebaut** [comment]
A quick comment on this issue:
I think that ITransportFactory must be package local at least.
I would also remove the implements ITransportFactory from JadbConnection and add a ITransportFactory getTransportFactory() in JadbConnection (package private)

What do you think about it ?

**Comment by thangdc94** [comment]
@bcallebaut You are right. `Transport` is package access, so its factory method should be package access. 

Factory method should be placed in indivudal class rather implement it in `JadbConnection`.

**Comment by bcallebaut** [comment]
Could you have a look at the commit in my fork : bcallebaut/jadb with id [bb7006a](https://github.com/bcallebaut/jadb/commit/bb7006a87fb9b78be4b345a19e575b61eaa9fb86) before I do a Pull Request

 Any comment is welcome (blame too btw)

**Comment by vidstige** [comment]
Nice! But what's the point of the extra class? 🤔 Who is actually using the `createTransport` method outside the class? Let's look at that first. Then fixing this issue can be a single line - Just changing the access modifier to package (or private) for `createTransport`.

**Comment by vidstige** [comment]
To be honest, I don't remember why I added the `ITransportFactory` interface. But it should be easy to check how it's used, and go from there. If it's only used by the `JadbConnection` then I feel we can drop the interface actually.

**Comment by thangdc94** [comment]
@vidstige Yeah, It is better to remove it. 
@bcallebaut Can you remove `ITransportFactory` and its Implementation in your pull request?

**Comment by thangdc94** [comment]
Hi @bcallebaut ,
You forgot to change access modifier of `createTransport()` to package 
https://github.com/bcallebaut/jadb/blob/2d24394233a951e9ff0a8235488be7c054e256a4/src/se/vidstige/jadb/JadbConnection.java#L26

**Comment by bcallebaut** [comment]
Hi @thangdc94, Change done. Indeed, I forgot it.

**Comment by vidstige** [comment]
Everything seems to be in order here.
