### ISSUE TITLE
implement AutoCloseable in Transport

### ISSUE THREAD

**Issue by thangdc94** [vidstige/jadb#76]
I think implementation of `Socket `should implement interface `AutoCloseable `  (introduced in Java 7) to make it possible to use try-with-resources idiom.

What do you think?

**Comment by bcallebaut** [comment]
@thangdc94 : Good remark, could you point me to the code you are talking about ?

**Comment by thangdc94** [comment]
@bcallebaut This class should implement `AutoClosable`
https://github.com/vidstige/jadb/blob/master/src/se/vidstige/jadb/Transport.java

**Comment by bcallebaut** [comment]
I made the change you requested as part of Pull Request #77.
