### ISSUE TITLE
New JADB release

### ISSUE THREAD

**Issue by mikita-simanavets** [vidstige/jadb#78]
Hello @vidstige!

Master branch contains 51 new commits since [v1.0.1 release](https://github.com/vidstige/jadb/releases/tag/v1.0.1) [Nov 9, 2016]. 
Could you please say, when do you plan to release new version of JADB?

**Comment by mikita-simanavets** [comment]
@SKART1 thank you a lot! Yes, JitPack doing what a want

```
dependencies {
    compile 'com.github.vidstige:jadb:master-SNAPSHOT'
}
```

**Comment by SKART1** [comment]
It is better to refer "stable"  artifact if you are dealing with any build system. It guarantees same result for two builds. 
Snapshot may refer to new artifact with new features/bugs, while referring commit will guarantee same jar
Try something like this:
```
dependencies {
    compile 'com.github.vidstige:jadb:master-f9cfdfa419'
}
```

**Comment by vidstige** [comment]
Wow, time really flies doesn't it? We should definitely make a new release with all the good stuff. Just to get a small sample here. Are you using the latest? Does it work well? If so I can tag a new release right away.

**Comment by mikita-simanavets** [comment]
Guys, it looks like you forgot to make a release. There is no information about new version at [Releases page](https://github.com/vidstige/jadb/releases) and at [JitPack repository](https://jitpack.io/#vidstige/jadb) (both show v1.0.1 as latest). Please, make it. If I can help with it, let me know. Thank you!

**Comment by vidstige** [comment]
Oh, I thought all tags where automatically released. I just quickly summarized all the commits in a new relase - v1.1.0. I don't know if jitpack will pick it up, but lets keep an eye out.

Also do you gentlemen know of master should look? Should there be `"1.2-SNAPSHOT"` in the pom.xml file? 🤔

**Comment by SKART1** [comment]
It is already in jitpack:
![image](https://user-images.githubusercontent.com/3259560/40322462-23151ab2-5d3b-11e8-9461-9551157e51eb.png)


What about pom.xml - there are different approaches but as for me the best way is to keep current version + SNAPSHOT string inside pom.xml

**Comment by vidstige** [comment]
Alright, cool. With "current", you mean the last released version or the version currently in the making? Are we good to go for now, in that case? Or should we go `"1.2-SNAPSHOT"`?

**Comment by SKART1** [comment]
I mean "the last released version" - but it is my IMHO based on discussions of pro and con of both approaches

**Comment by vidstige** [comment]
Alright. I've also heard sensible for going with with the _upcoming_ version, but lets go with this for now. Thanks for the initiative and help guys.
