### ISSUE TITLE
PackageManager problems

### ISSUE THREAD

**Issue by janosvitok** [vidstige/jadb#84]
# Issue 1: all options get space appended
# Issue 2: option parameter is joined with the value:

https://github.com/vidstige/jadb/blob/312cd0235a82faee2928920c2c6077c1538f9bbb/src/se/vidstige/jadb/managers/PackageManager.java#L100

```
WITH_FORWARD_LOCK.getStringRepresentation() -> "-l "
WITH_INSTALLER_PACKAGE_NAME("aaa bbb").getStringRepresentation() -> "-t aaa bbb"
```
that JadbDevice.buildCmdLine turns to
```
'-l '
'-t aaa bbb'
```
while most probably it should be
```
-l
-t 'aaa bbb'
```

# Issue 3: Bash.quote() in PackageManager.remove() probably causes double quoting.

# ~~Issue 4: Bash.quote itself propably does not quote well~~
~~`Bash.quote("-t 'aaa'") ->"'-t '\'aaa\'''"`~~
Edit: I've [learned](http://wiki.bash-hackers.org/syntax/quoting#strong_quoting) that the code is correct.
I've create PR #90 with a test for this.

# Possible fixes
Easy fix Issue 1 is to add 
```
            stringBuilder.deleteCharAt(stringBuilder.length() -1);
```
at the end of InstallOption constructor.

Fix for Issue 2 (will fix Issue 1) is to store String[] and just pass unprocessed them from installWithOptions() through install() to executeShell() that will add spaces and quotes anyway.

**Comment by vidstige** [comment]
All but one problem remaining. Moved it to separate issue for clarity - #105.
