### ISSUE TITLE
CONTRIBUTING.md is outdated

### ISSUE THREAD

**Issue by janosvitok** [vidstige/jadb#87]
The CONTRIBUTING.md is bit outdated - you can't build with ant now, you should with maven, etc.

Also: build.xml should be updated (at least update java version to match maven) or deleted

Also: coding guidelines would be appreciated
* what Java version compatibility do you go for? Can we use Java 7/8/9/10/... features? From maven config I guess 1.7...

**Comment by SKART1** [comment]
I think we may set source compatibility to java 1.8 which features are mostly common to android programmers

What about ant - may be it is time to drop it`s support - cause maven do same + some extra features. 
@vidstige - what do you think about ant?

**Comment by vidstige** [comment]
Yes, I doubt anyone uses the `ant` build anymore. Even travis uses maven as can be seen in the [build log](https://travis-ci.org/vidstige/jadb). It won't be missed - Lets burn it with fire! :-)

**Comment by vidstige** [comment]
As for java compatibility, as this is library that does not see super much development, being compatible is more worth than somewhat cleaner code. I'm not against 1.8, but this is not an app or so, and you can still use this library in your 1.8 Java android app or whatever. The compatibility is just the _minimum_ version needed. Unless a very compelling argument can be made to drop compatibility, I feel staying on 1.6 (or whatever current version is) is a better choice for the people using the library.

**Comment by janosvitok** [comment]
Maven specs 1.7, ant specs 1.6 but fails to build the source due to diamond operator:

```
compile.module.jadb.production:
    [mkdir] Created dir: XXX\jadb\bin
    [javac] XXX\jadb\module_jadb.xml:65: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 28 source files to XXX\jadb\bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] XXX\jadb\src\se\vidstige\jadb\managers\PackageManager.java:58: error: diamond operator is not supported in -source 1.6
    [javac]         ArrayList<String> arguments = new ArrayList<>();
    [javac]                                                     ^
    [javac]   (use -source 7 or higher to enable diamond operator)
    [javac] XXX\jadb\src\se\vidstige\jadb\managers\PropertyManager.java:26: error: try-with-resources is not supported in -source 1.6
    [javac]         try (BufferedReader bufferedReader =
    [javac]             ^
    [javac]   (use -source 7 or higher to enable try-with-resources)
    [javac] XXX\jadb\src\se\vidstige\jadb\managers\PropertyManager.java:33: error: diamond operator is not supported in -source 1.6
    [javac]         HashMap<String, String> result = new HashMap<>();
    [javac]                                                      ^
    [javac]   (use -source 7 or higher to enable diamond operator)
    [javac] 3 errors
    [javac] 1 warning

BUILD FAILED
```

**Comment by vidstige** [comment]
There you go, just one more reason to rip it out 👍

**Comment by vidstige** [comment]
Pull requests open for business! I won't have time to remove it personally during upcoming weeks, but perhaps later on.

**Comment by vidstige** [comment]
Adressed in #104
