### ISSUE TITLE
 JadbException e ;List<JadbDevice> devices = jadb.getDevices();

### ISSUE THREAD

**Issue by luoshiduan** [vidstige/jadb#96]
please, I have a question: when I use the funcation List<JadbDevice> devices = jadb.getDevices() it catch that JadbException??

**Comment by kingz3** [comment]
you probably already figured this out but functions can throw exceptions not catch them so you would have to catch that jadb Exception

**Comment by vidstige** [comment]
Can you clarify your question? What is the exception _message_? Please provide full stacktrace of the error.
